main: br.com.eterniaserver.eterniaserver.EterniaServer
name: EterniaServer
version: 2.0.0-STABLE
author: Yuri Nogueira
description: Blablabla
load: STARTUP
api-version: '1.14'
website: www.eterniaserver.com.br
depend: [EterniaLib, PlaceholderAPI]
softdepend: [Vault, ChestShop]