language: java
addons:
  sonarcloud:
    organization: eterniaserver
    token:
      secure: PtavWzDGYZbxPpEBxv/cjJNey6aFL5Gt6AqUnH/uLRD6Eg0xIZPmOU4PCzBz8SyzbQDi7W52Ua1yjhHbDpeJdwMHWD5u0xvbut2aYyzTnRYnUZkgL8qYED0CulWv0/jeP3TbQ6yHOCOhfDzsOvzVRSiAKpQVBSeniGgrQumPc9+HlSfbE2ILrZzln2+fPueQ9OAhvgG4j5M/DJvlTd3huf4GUu3U3OyMTYq5FXhUBXyzhJdU25EttxXsiosRyixg2FoWo0cBha1nL3XvGBXZVDpRs+k1HtMuVidakiHaAx1hDj5kWuLk4n374+WvJBOpzKrAZXEqwhdY9935HBYI+SNbyTQO10snNYvOghU2V1k1fORxn5DU31K9vlJBwu6ssgjICisNYGJsGwNBbIoeJpz5iFGeoepE/0tnj5Whf8jpxVmlRY0Puj6UnrAfIC98foqXYHpMectyAEv2+baFn8FxK9XZ/REtX/IkJfv2o4y9wT7yNEc92YT65v1KluM511zDD/HXhrve3wliVSjohldxDUU62bRrdncWJhzHeQriErF7JI/q/wrkCiEweH9jw1xA0bVHPFKJOJMt/ZxwAx70FCpuqNKSE+fUi1q51xiifOYuVgWwwg8xPoiydXtQJw+t1GRBs6KwS8ViFV1ILMRx2HAKtxXoefNoJOpq5Bg=
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=EterniaServer_EterniaServer
jdk:
  - openjdk8
env:
  global:
    secure: PtavWzDGYZbxPpEBxv/cjJNey6aFL5Gt6AqUnH/uLRD6Eg0xIZPmOU4PCzBz8SyzbQDi7W52Ua1yjhHbDpeJdwMHWD5u0xvbut2aYyzTnRYnUZkgL8qYED0CulWv0/jeP3TbQ6yHOCOhfDzsOvzVRSiAKpQVBSeniGgrQumPc9+HlSfbE2ILrZzln2+fPueQ9OAhvgG4j5M/DJvlTd3huf4GUu3U3OyMTYq5FXhUBXyzhJdU25EttxXsiosRyixg2FoWo0cBha1nL3XvGBXZVDpRs+k1HtMuVidakiHaAx1hDj5kWuLk4n374+WvJBOpzKrAZXEqwhdY9935HBYI+SNbyTQO10snNYvOghU2V1k1fORxn5DU31K9vlJBwu6ssgjICisNYGJsGwNBbIoeJpz5iFGeoepE/0tnj5Whf8jpxVmlRY0Puj6UnrAfIC98foqXYHpMectyAEv2+baFn8FxK9XZ/REtX/IkJfv2o4y9wT7yNEc92YT65v1KluM511zDD/HXhrve3wliVSjohldxDUU62bRrdncWJhzHeQriErF7JI/q/wrkCiEweH9jw1xA0bVHPFKJOJMt/ZxwAx70FCpuqNKSE+fUi1q51xiifOYuVgWwwg8xPoiydXtQJw+t1GRBs6KwS8ViFV1ILMRx2HAKtxXoefNoJOpq5Bg=
