language: java
addons:
  sonarcloud:
    organization: eterniaserver
    token:
      secure: $SONAR_CLOUD_TOKEN
jobs:
  include:
    - stage: "Unit Tests & SonarCloud Analysis"
      script:
        - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
jdk:
  - openjdk16
