language: java
addons:
  sonarcloud:
    organization: eterniaserver
    token:
      secure: "$SONAR_CLOUD_TOKEN"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=EterniaServer_EterniaServer
jdk:
  - openjdk16
