language: java
addons:
  sonarcloud:
    organization: eterniaserver
    token:
      secure: $SONAR_CLOUD_TOKEN
jobs:
  include:
    - stage: "Unit Tests & SonarCloud Analysis"
      script:
        - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.login=$SONAR_CLOUD_TOKEN -Dsonar.projectKey=EterniaServer_EterniaServer
jdk:
  - openjdk16
