package br.com.eterniaserver.eterniaserver.enums;

public enum Booleans {

    MODULE_BED,
    MODULE_BLOCK,
    MODULE_CASH,
    MODULE_CHAT,
    MODULE_ENTITY,
    MODULE_COMMANDS,
    MODULE_ECONOMY,
    MODULE_ELEVATOR,
    MODULE_EXPERIENCE,
    MODULE_HOMES,
    MODULE_SHOP,
    MODULE_KITS,
    MODULE_SPAWNERS,
    MODULE_TELEPORTS,
    MODULE_REWARDS,
    MODULE_SCHEDULE,
    MODULE_GENERIC,
    CHEST_SHOP_SUPPORT,
    ASYNC_CHECK,
    AFK_KICK,
    INV_DROP,
    BLOCK_BREAK_SPAWNERS,
    ITEMS_FUNCTIONS,
    PREVENT_ANVIL,
    CLEAR_ENTITIES,
    ENTITY_LIMITER,
    BREEDING_LIMITER,
    ENTITY_EDITOR

}
