package br.com.eterniaserver.eterniaserver.enums;

public enum Booleans {

    MODULE_CASH,
    MODULE_ELEVATOR,
    MODULE_EXPERIENCE,
    MODULE_GLOW,
    MODULE_SPAWNERS,
    MODULE_REWARDS,
    MODULE_PAPI,
    MODULE_ENTITY,
    MODULE_ECONOMY,
    MODULE_BED,
    MODULE_ITEM,
    MODULE_KIT,
    MODULE_TELEPORT,
    MODULE_CHAT,
    HAS_ECONOMY_PLUGIN,
    AFK_KICK,
    INV_DROP,
    BLOCK_BREAK_SPAWNERS,
    PREVENT_ANVIL,
    CLEAR_ENTITIES,
    ENTITY_LIMITER,
    BREEDING_LIMITER,
    ENTITY_EDITOR,
    ECONOMY_HAS_BANK,
    CUSTOM_COMMANDS,

}
