package br.com.eterniaserver.eterniaserver.enums;

public enum ConfigLists {

    BLACKLISTED_WORLDS_FLY,
    BLACKLISTED_WORLDS_SLEEP,
    BLACKLISTED_WORLDS_SPAWNERS,
    BLACKLISTED_BALANCE_TOP,
    BLACKLISTED_COMMANDS,
    PROFILE_CUSTOM_MESSAGES

}
