package br.com.eterniaserver.eterniaserver.enums;

public enum Lists {

    BLACKLISTED_WORLDS_FLY,
    BLACKLISTED_WORLDS_SLEEP,
    BLACKLISTED_WORLDS_SPAWNERS,
    BLACKLISTED_WORLDS_BACK,
    BLACKLISTED_BALANCE_TOP,
    BLACKLISTED_COMMANDS,
    PROFILE_CUSTOM_MESSAGES,
    TITLE_LIST,
    MINI_MESSAGES_BOTTLE_EXP_LORE

}
