modules:
  generic: true
  tpa: true
  warp: true
  xp: true
sql:
  mysql: false
  host: '127.0.0.1'
  database: 'admin'
  user: 'admin'
  password: 'admin'
money:
  start: 300
  back: 2500
  singular: 'Eternia'
  plural: 'Eternias'
server:
  nether-check: 1
  cooldown: 4
spawners:
  mob-name-color: '&e'
  lore:
    - '&7Coloque isso no chão&8.'
    - '&3%s &7spawner&8.'
  enable-lore: false
  prevent-anvil: true
  blacklisted-worlds:
    - 'shop'
  log: true
  drop-in-inventory: true
  drop-chance: 1.0
# Spawn
world-n: 'world'
x-n: 0
y-n: 70
z-n: 0
yaw-n: 0
pitch-n: 0
# Evento
world-e: 'world'
x-e: 0
y-e: 70
z-e: 0
yaw-e: 0
pitch-e: 0
# Arena
world-a: 'world'
x-a: 0
y-a: 70
z-a: 0
yaw-a: 0
pitch-a: 0
# Caixa
world-c: 'world'
x-c: 0
y-c: 70
z-c: 0
yaw-c: 0
pitch-c: 0
# Loja
world-s: 'world'
x-s: 0
y-s: 70
z-s: 0
yaw-s: 0
pitch-s: 0