# Configs MIST
xp-module: true
warp-module: true
tpa-module: true
intervalo: 1
cooldown: 4
valor-do-back: 5000
mysql: false
host: '127.0.0.1'
porta: 3306
database: 'admin'
usuario: 'admin'
senha: 'admin'
# Spawn
world: 'world'
x: 0
y: 70
z: 0
yaw: 0
pitch: 0
# Evento
world-e: 'world'
x-e: 0
y-e: 70
z-e: 0
yaw-e: 0
pitch-e: 0
# Arena
world-a: 'world'
x-a: 0
y-a: 70
z-a: 0
yaw-a: 0
pitch-a: 0
# Caixa
world-c: 'world'
x-c: 0
y-c: 70
z-c: 0
yaw-c: 0
pitch-c: 0