# Intervalo para verificar se o jogador está preso em uma trap com portal do nether em segundos
intervalo: 1
# Valor do comando /back para membros que não tem a permissão eternia.backfree
valor-do-back: 5000
# Se ativado será usada database MySQL
mysql: false
host: '127.0.0.1'
porta: 3306
database: 'admin'
usuario: 'admin'
senha: 'admin'
# Spawn
cooldown: 4
world: 'world'
x: 0
y: 70
z: 0
yaw: 0
pitch: 0
# Evento
world-e: 'world'
x-e: 0
y-e: 70
z-e: 0
yaw-e: 0
pitch-e: 0
# Arena
world-a: 'world'
x-a: 0
y-a: 70
z-a: 0
yaw-a: 0
pitch-a: 0
# Caixa
world-c: 'world'
x-c: 0
y-c: 70
z-c: 0
yaw-c: 0
pitch-c: 0
# Mensagens
sem-permissao: '&8[&aE&9S&8] &7Você não tem permissão para isso&8.'
spawn: '&8[&aE&9S&8] &7Bem-vindo ao spawn&8.'
trap-mensagem-tempo: '&8[&aE&9S&8] &7Armadilha encontrada&8, &7se teleportando para o spawn em&3 %s &7segundos&8.'
back-gratis: '&8[&aE&9S&8] &7Você voltou aonde estava de graça&8.'
back-nao-pode: '&8[&aE&9S&8] &7Você ainda não se teleportou&8.'
back-sem-dinheiro: '&8[&aE&9S&8] &7Você não possui eternias suficiêntes&8,&7 você precisa de &3%s&8.'
back-sucesso: '&8[&aE&9S&8] &7Você voltou aonde estava e isso custou &3%s &7eternias&8.'
xp-sucesso: '&8[&aE&9S&8] &7Toma ai suas garrafinhas&8!'
xp-insuficiente: '&8[&aE&9S&8] &7Você não tem EXP suficiênte&8.'
xp-guardado: '&8[&aE&9S&8] &7Pronto você guardou &3%s &7de EXP&8.'
xp-tirar: '&8[&aE&9S&8] &7Pronto seu nível agora é &3%s&8.'
cores: '&8[&aE&9S&8] &7&&aa &7&&bb &7&&cc &7&&dd &7&&ee &7&&ff &7&&00 &7&&11 &7&&22 &7&&33 &7&&44 &7&&55 &7&&66 &7&&77 &7&&88 &7&&99&8.'
guarda-level: '&8[&aE&9S&8] &7Use &6/guardalvl &3<quantia>&8.'
guarda-level-errou: '&8[&aE&9S&8] &7Use &6/guardalvl &3<quantia>&8, &7vamos lá&8,&7 não é difícil&8.'
discord: '&8[&aE&9S&8] &7Entre em nosso discord&8: &3https://discord.gg/Qs3RxMq&8.'
doacao: '&8[&aE&9S&8] &7Olá&8, &7você pode fazer uma doação via transferência bancária&8, &7boleto ou cartão&8, &7entre no discord e fale com yurinogueira&8.'
facebook: '&8[&aE&9S&8] &7Entre em nosso facebook&8: &3https://facebook.com/eterniaserver&8.'
pa-falta-tempo: '&8[&aE&9S&8] &7Você deve esperar &3%s &7segundos para poder usar esse comando novamente&8.'
pa-sucesso: '&8[&aE&9S&8] &7Toma sua pá&8!'
capacete: '&8[&aE&9S&8] &7Aproveite seu novo Caçapete&8.'
suicidio: '&8[&aE&9S&8] &3%s &7disse antes de tirar sua própria vida&8.'
aviso: '&8[&aE&9S&8] &7Use &6/aviso &3<mensagem>&8.'
aviso-global: '&8[&aE&9S&8] &7%s'
jogador-offline: '&8[&aE&9S&8] &7O jogador não está online&8.'
encheu-barra: '&8[&aE&9S&8] &7Você saciou o jogador &3%s&8.'
recebeu-barra: '&8[&aE&9S&8] &7Você foi saciado por &3%s&8.'
me-enchi: '&8[&aE&9S&8] &7Você se saciou&8.'
ativar-voar: '&8[&aE&9S&8] &7Voar ativado&8.'
desativar-voar: '&8[&aE&9S&8] &7Voar desativado&8.'
ativar-voar-de: '&8[&aE&9S&8] &7Você ativou o voar de &3%s&8.'
desativar-voar-de: '&8[&aE&9S&8] &7Você desativou o voar de &3%s&8.'
ativaram-voar: '&8[&aE&9S&8] &3%s &7ativou seu voar&8.'
desativaram-voar: '&8[&aE&9S&8] &3%s &7desativou seu voar&8.'
nick-novo: '&8[&aE&9S&8] &7Seu apelido alternativo é &3%s&8.'
nick-removido: '&8[&aE&9S&8] &7Apelido alternativo removido&8.'
escondido: '&8[&aE&9S&8] &7Shiii&8, &7agora você está escondido&8.'
jogando: '&8[&aE&9S&8] &7Agora você está jogando novamente&8.'
teleportando-em: '&8[&aE&9S&8] &7Você será teleportado em &3%s &7segundos&8.'
spawn-definido: '&8[&aE&9S&8] &7Spawn definido&8.'
teleportou-ele: '&8[&aE&9S&8] &7Você teleportou &3%s&8.'
feito: '&8[&aE&9S&8] &7:)&8.'
sem-evento: '&8[&aE&9S&8] &7Não há nenhum evento no momento&8.'
evento: '&8[&aE&9S&8] &7Indo para o evento :)&8!'
arena: '&8[&aE&9S&8] &7Indo para a arena&8, &7cuidado&8.'
caixa: '&8[&aE&9S&8] &7Indo para as caixas&8.'
evento-definido: '&8[&aE&9S&8] &7Evento definido&8.'
arena-definida: '&8[&aE&9S&8] &7Arena definida&8.'
caixa-definida: '&8[&aE&9S&8] &7Caixa definida&8.'
precisa-numero: '&8[&aE&9S&8] &7Bem... o número da página precisa ser um número&8.'
proxima-pagina: '&8[&aE&9S&8] &7Use &6/regras &3%s &7para ir para a proxima página&8.'
pagina-negativa: '&8[&aE&9S&8] &7Página negativa não existe né amigo&8, &7nem &30&8.'
teleportou-geral: '&8[&aE&9S&8] &3%s &7teleportou a todos até si&8.'
somente-jogador: '&8[&aE&9S&8] &7Somente jogadores podem usar isso&8.'
vault-off: '&8[&aE&9S&8] &7Vault não encontrado&8, &7desativando EterniaServer&8.'
conectado-sucesso-mysql: '&8[&aE&9S&8] &7Conectado com sucesso a database &3MySQL&8.'
conectado-sucesso-sql: '&8[&aE&9S&8] &7Conectado com sucesso a database &3SQLite&8.'
erro-sqlite: "&8[&aE&9S&8] &7Erro ao criar arquivo &3%s&8."
regras: '&8[&aE&9S&8] &7Regras/split/
&91.0 &8- &7Proibido ofensas&8./split/
&91.1 &8- &7Qualquer forma de preconceito é proibida&8./split/
&91.2 &8- &7Proibido apologia a coisas ofensiva e&8/&7ou que trouxeram uma grande perda para a sociedade&8./split/
&92.0 &8- &7Proibido o uso de apelido impropriado&8./split/
&92.1 &8- &7A mesma regra se aplica a pets e etc&8./split/
&93.0 &8- &7Proibido o uso de qualquer hack&8,&7 exploit e etc&8./split/
&93.1 &8- &7Aproveitar-se ou esconder um bug também é proibido&8./split/
&93.2 &8- &7O ato de má fé também é proibido&8./split/
&94.0 &8- &7Proibido enganações&8./split/
&94.1 &8- &7Certas traps são enganações sendo também proibido&8./split/
&94.2 &8- &7Certas promessas também são consideradas enganação&8./split/
&95.0 &8- &7Proibido se intrometer em assuntos pessoais e assuntos da Staff&8./split/
&96.0 &8- &7Proibido pedir itens&8,&7 permissões e etc&8./split/
&96.1 &8- &7O mesmo se aplica para cargos&8./split/
&97.0 &8- &7Evitar falar vulgamente e&8/&7ou explicitamente sobre sexo no chat global&8./split/
&98.0 &8- &7Proibido apologia a coisas ilícitas&8,&7 inclusive programas&8./split/
&99.0 &8- &7Proibido flood&8/&7spam&8./split/
&99.1 &8- &7Proibido discutir sobre a punição dada ou não dada por um staff&8.'
votar: '&8[&aE&9S&8] &7Sites&8:/split/
&9https://minecraft-mp.com/server-s229257&8./split/
&9https://topg.org/server-eterniaserver-id484008&8./split/
&9https://www.planetminecraft.com/server/eterniaserver/&8./split/
&9https://minecraftservers.biz/servers/144674/&8.'