#  _______ .___________. _______ .______      .__   __.  __       ___
# |   ____||           ||   ____||   _  \     |  \ |  | |  |     /   \
# |  |__   `---|  |----`|  |__   |  |_)  |    |   \|  | |  |    /  ^  \
# |   __|      |  |     |   __|  |      /     |  . `  | |  |   /  /_\  \
# |  |____     |  |     |  |____ |  |\  \----.|  |\   | |  |  /  _____  \
# |_______|    |__|     |_______|| _| `._____||__| \__| |__| /__/     \__\

# bed contain the bed module to skip night.
# block-reward will enable or disable the rewards for break certain
# types of blocks.
# commands will enable or disable the custom commands module.
# economy will enable or disable the economy module.
# experience will enable or disable the experience module.
# generic will enable or disable the common commands.
# home will enable or disable the home module.
# spawners will enable or disable to get and place spawners.
# teleports will enable or disable warps, teleportoplayer and others.
modules:
  bed: true
  block-reward: true
  cash: true
  chat: true
  commands: true
  economy: true
  elevator: true
  experience: true
  home: true
  kits: true
  spawners: true
  teleports: true
  rewards: true

# Placeholders for PlaceholderAPI.
placeholders:
  afk: '&9 AFK'
  godmode: '&9 GOD'

# async-check will enable the async method.
# don't know what you're doing.
# checks is the interval between checks, like afk, anti nether trap, cooldowns
# don't touch this, if you don't know what you're doing.
# afk-timer is the time in seconds for player be kicked by afk.
# cooldown is the interval between the player being teleported when using a
# command that teleports him.
server:
  async-check: true
  checks: 1
  afk-timer: 900
  afk-kick: true
  cooldown: 4
  pvp-time: 15

# The blocks you choose will be able to be elevators if have another of the
# same type above or bellow.
# max is the max distance.
# min is the min distance.
elevator:
  block:
    - 'IRON_BLOCK'
  max: 50
  min: 2

# With this you can choose between using MySQL or SQLite and
# define the name of each table.
sql:
  table-xp: 'es_exp'
  table-money: 'es_money'
  table-warp: 'es_warps'
  table-shop: 'es_shops'
  table-home: 'es_users_homes'
  table-homes: 'es_homes_location'
  table-kits: 'es_kits'
  table-player: 'es_users_profile'
  table-muted: 'es_muted'
  table-rewards: 'es_rewards'
  table-nick: 'es_users_nick'
  table-cash: 'es_users_cash'

# speed is how faster the night will pass (this will be divided by the (players
# online divided by the players sleeping))
# blacklisted-worlds will set which worlds could not skip the night sleeping.
bed:
  speed: 100
  blacklisted-worlds:
    - 'evento'

# start is the amount of money the player will have when starting.
# back is the cost of the /back command.
# singular is the name of the currency in the singular.
# plural is the name of the currency in the plural.
# no-baltop is the name of the bank account.
money:
  start: 300
  back: 1000
  nick: 500000
  singular: 'Eternia'
  plural: 'Eternias'
  no-baltop:
    - 'YuriNogueira'

# This commands will be blocked.
blocked-commands:
  - '/op'
  - '/deop'
  - '/stop'

# mob-name-color is the color of the mobs name in the mobspawner.
# enable-lore will enable or disable lore of mobspawners.
# lore is the lore of mobspawner.
# drop-in-inventory will make the mobspawner go to the inventory instead of
# the ground.
# drop-chance is the chance of drop a mobspawner, 1.0 == 100%.
# prevent-anvil will block the option to rename a mobspawner.
# blacklisted-worlds will block to get a mobspawner in the listed worlds.
# log will report to console all mobspawners placed.
spawners:
  mob-name-color: '&e'
  drop-in-inventory: true
  drop-chance: 1.0
  prevent-anvil: true
  blacklisted-worlds:
    - 'evento'
  log: true
