modules:
  generic: true
  tpa: true
  warp: true
  xp: true
sql:
  mysql: false
  host: '127.0.0.1'
  database: 'admin'
  user: 'admin'
  password: 'admin'
money:
  start: 300
  back: 2500
  singular: 'Eternia'
  plural: 'Eternias'
server:
  nether-check: 1
  cooldown: 4
spawners:
  mob-name-color: '&e'
  lore:
    - '&7Coloque isso no chão&8.'
    - '&3%s &7spawner&8.'
  enable-lore: false
  prevent-anvil: true
  blacklisted-worlds:
    - 'shop'
  log: true
  drop-in-inventory: true
  drop-chance: 1.0
