#  _______ .___________. _______ .______      .__   __.  __       ___
# |   ____||           ||   ____||   _  \     |  \ |  | |  |     /   \
# |  |__   `---|  |----`|  |__   |  |_)  |    |   \|  | |  |    /  ^  \
# |   __|      |  |     |   __|  |      /     |  . `  | |  |   /  /_\  \
# |  |____     |  |     |  |____ |  |\  \----.|  |\   | |  |  /  _____  \
# |_______|    |__|     |_______|| _| `._____||__| \__| |__| /__/     \__\

# playerchecks contain importants checks, please don't disable.
# bed contain the bed module to skip night.
# block-reward will enable or disable the rewards for break certain
# types of blocks.
# economy will enable or disable the economy module.
# experience will enable or disable the experience module.
# generic will enable or disable the common commands.
# home will enable or disable the home module.
# spawners will enable or disable to get and place spawners.
# teleports will enable or disable warps, teleportoplayer and others.
modules:
  playerchecks: true
  bed: true
  block-reward: true
  economy: true
  experience: true
  generic: true
  home: true
  spawners: true
  teleports: true

# async-check will enable the async method, please don't disable it if you
# don't know what you're doing.
# checks is the interval between checks, like afk or anti nether trap, don't
# user this lower than 2.
# afk-timer is the time in seconds for player be kicked by afk.
# cooldown is the interval between the player being teleported when using a
# command that teleports him.
server:
  async-check: true
  checks: 2
  afk-timer: 900
  cooldown: 4

# With this you can choose between using MySQL or SQLite and
# define the name of each table.
sql:
  mysql: false
  host: '127.0.0.1'
  port: '3306'
  database: 'admin'
  user: 'admin'
  password: 'admin'
  table-xp: 'es_xp'
  table-money: 'es_economy'
  table-warp: 'es_warp'
  table-shop: 'es_shop'
  table-home: 'es_home'
  table-homes: 'es_homes'

# This will set which worlds could not skip the night sleeping.
bed:
  blacklisted-worlds:
    - 'evento'

# start is the amount of money the player will have when starting.
# back is the cost of the /back command.
# singular is the name of the currency in the singular.
# plural is the name of the currency in the plural.
money:
  start: 300
  back: 2500
  singular: 'Eternia'
  plural: 'Eternias'

# mob-name-color is the color of the mobs name in the mobspawner.
# enable-lore will enable or disable lore of mobspawners.
# lore is the lore of mobspawner.
# drop-in-inventory will make the mobspawner go to the inventory instead of
# the ground.
# drop-chance is the chance of drop a mobspawner, 1.0 == 100%.
# prevent-anvil will block the option to rename a mobspawner.
# blacklisted-worlds will block to get a mobspawner in the listed worlds.
# log will report to console all mobspawners placed.
spawners:
  mob-name-color: '&e'
  enable-lore: false
  lore:
    - '&7Coloque isso no chão&8.'
    - '&3%s &7spawner&8.'
  drop-in-inventory: true
  drop-chance: 1.0
  prevent-anvil: true
  blacklisted-worlds:
    - 'evento'
  log: true
