main: br.com.eterniaserver.eterniaserver.EterniaServer

name: EterniaServer
version: '${project.version}'
author: Yuri Nogueira
description: Blablabla
api-version: '1.16'
softdepend: [EterniaLib, Vault, PlaceholderAPI]