main: br.com.eterniaserver.eterniaserver.EterniaServer

name: EterniaServer
version: '${project.version}'
author: Yuri Nogueira
description: Blablabla
api-version: '1.13'
depend: [EterniaLib, Vault, PlaceholderAPI]
softdepend: [EterniaMarriage]