main: br.com.eterniaserver.eterniaserver.EterniaServer

name: EterniaServer
version: '${project.version}'
author: Yuri Nogueira
description: Blablabla
api-version: '1.15'
load: STARTUP
softdepend: [Vault, PlaceholderAPI]