main: br.com.eterniaserver.EterniaServer

name: EterniaServer
version: '${project.version}'
author: Yuri Nogueira
description: Blablabla
api-version: '1.15'
softdepend: [Vault, PlaceholderAPI]
loadbefore: [VentureChat]
commands:
  suicide:
    description: Se mate.
    aliases: [suicidio, killme]
  advice:
    description: Avise.
    aliases: [broadcast, aviso, anuncio]
  feed:
    description: Alimenta.
    aliases: [heal, fome]
  hat:
    description: Capacete.
    aliases: [capacete]
  fly:
    description: Voe.
    aliases: [voar, ativarvoar, ativarfly]
  depositlvl:
    description: Guarde xp.
    aliases: [armazenarxp, guardalvl, armazenarlvl]
  withdrawlvl:
    description: Tira o xp.
    aliases: [tirarxp, retirarlvl, tirarlvl, pegarlvl]
  goldenshovel:
    description: Pega uma comandos.eternia.player.pa.
    aliases: [padeouro, pa]
  blocks:
    description: Transforma em bloco.
    aliases: [condenser, transformarembloco]
  back:
    description: Volta aonde morreu.
    aliases: [dback, voltarmorte]
  bottlexp:
    description: Garrafinhas de xp.
    aliases: [garrafinhas]
  teleportaccept:
    description: Aceita o tpa.
    aliases: [tpaccept, aceitartpa]
  teleportdeny:
    description: Nega o tpa.
    aliases: [tpdeny, negartpa]
  teleporttoplayer:
    description: Envia pedido de tpa.
    aliases: [tpa]
  checklevel:
    description: Verifica o saldo guardado.
    aliases: [verxp, checkxp, xpguardado]
  pay:
    description: Paga alguem.
    aliases: [pagar]
  money:
    description: Ve seu ou de outro dinheiro.
    aliases: [balance]
  baltop:
    description: Ve o top money.
    aliases: [topmoney]
  eco:
    description: Meche na economia.
    aliases: [ecochange]
  spawnergive:
    description: Da um spawner.
    aliases: [darspawner]
  gamemode:
    description: Altera o gamemode de um jogador.
    aliases: [gm]
  rain:
    description: Altera o clima para chuvoso.
    aliases: [chuva]
  sun:
    description: Altera o clima para ensolarado.
    aliases: [sol]
  god:
    description: Ativa e desativa o godmode.
    aliases: [deus]
  thor:
    description: Puna as pessoas.
    aliases: [lightningbolt]
  warp:
    description: Vai para uma warp.
    aliases: [local]
  setwarp:
    description: Define uma warp.
    aliases: [setlocal]
  shop:
    description: Vai para uma loja.
    aliases: [loja]
  spawn:
    description: Se teleporta para o spawn.
    aliases: [inicio]
  setspawn:
    description: Define o spawn.
    aliases: [definirinicio]
  teleportall:
    description: Teleporta todos.
    aliases: [tpall]
  setshop:
    description: Define sua loja.
    aliases: [setloja]
  listwarp:
    description: Lista as warps.
    aliases: [warps, locais]
  delwarp:
    description: Deleta uma warp.
    aliases: [dellocal]
  itemrename:
    description: Renomeia um item.
    aliases: [renameitem]
  reloadeternia:
    description: Reinicia as configs.
    aliases: [eterniareload]
  enderchest:
    description: Abre o enderchest.
    aliases: [openender]
  openinventory:
    description: Abre o inventario de algum jogador.
    aliases: [openinv, invsee]
  workbench:
    description: Abre uma workbench.
    aliases: [craft]
  delhouse:
    description: Deleta uma home.
    aliases: [delhome, delcasa]
  house:
    description: Vai pra uma home.
    aliases: [casa, home]
  houses:
    description: Ve suas homes.
    aliases: [casas, homes]
  sethouse:
    description: Define uma home.
    aliases: [setcasa, sethome]
  tell:
    description: Manda uma mensagem privada.
    aliases: [msg, w, whisper, message, pm]
  resp:
    description: Manda uma resposta.
    aliases: [r]
  mem:
    description: Verifica status da jvm.
    aliases: [memoria]
  afk:
    description: Fica afk.
    aliases: [awayfromkeyboard]