main: br.com.eterniaserver.eterniaserver.EterniaServer

name: EterniaServer
version: '${project.version}'
author: Yuri Nogueira
description: Blablabla
load: STARTUP
api-version: '1.13'
website: www.eterniaserver.com.br
depend: [EterniaLib, Vault, PlaceholderAPI]