name: EterniaServer
version: '${version}'
main: br.com.eterniaserver.eterniaserver.EterniaServer
api-version: 1.19
load: STARTUP
author: Yuri Nogueira
description: Um plugin eterno.
website: www.eterniaserver.com.br