main: principal.main

name: EterniaServer
version: '1.5'
author: Yuri Nogueira
description: Blablabla
api-version: '1.14'
depend: [Vault]
commands:
  suicide:
    description: Se mate.
    aliases: [suicidio, killme]
  advice:
    description: Avise.
    aliases: [broadcast, anuncio, aviso]
  donation:
    description: Doe.
    aliases: [doacao, doar, comprarvip]
  discord:
    description: Discord.
    aliases: [contato]
  rules:
    description: Regras.
    aliases: [regras]
  feed:
    description: Alimenta.
    aliases: [heal, fome]
  hat:
    description: Capacete.
    aliases: [capacete]
  name:
    description: Nome.
    aliases: [nickname, mudarnome, nome, changenickname]
  fly:
    description: Voe.
    aliases: [voar, ativarvoar, ativarfly]
  depositlvl:
    description: Guarde xp.
    aliases: [armazenarxp, guardalvl, armazenarlvl]
  withdrawlvl:
    description: Tira o xp.
    aliases: [tirarxp, retirarlvl, tirarlvl, pegarlvl]
  goldenshovel:
    description: Pega uma comandos.player.pa.
    aliases: [padeouro, pa]
  blocks:
    description: Transforma em bloco.
    aliases: [condenser, transformarembloco]
  back:
    description: Volta aonde morreu.
    aliases: [dback, voltarmorte]
  spectator:
    description: Se esconde
    aliases: [inv, spect]
  survival:
    description: Se mostra
    aliases: [jogar, aparecer]
  facebook:
    description: Pagina do server.
    aliases: [paginadoface]