main: principal.main

name: EterniaServer
version: '1.3'
author: Yuri Nogueira
description: Blablabla
api-version: '1.14'
commands:
  suicide:
    description: Se mate.
    aliases: [suicidio, killme]
  advice:
    description: Avise.
    aliases: [broadcast, anuncio, aviso]
  doar:
    description: Doe.
    aliases: [doacao, comprarvip]
  discord:
    description: Discord.
    aliases: [contato]
  regras:
    description: Regras.
    aliases: [rules]
  feed:
    description: Alimenta.
    aliases: [heal, fome]
  hat:
    description: Capacete.
    aliases: [capacete]
  nome:
    description: Nome.
    aliases: [nickname, mudarnome, changenickname]
  fly:
    description: Voe.
    aliases: [voar, ativarvoar, ativarfly]
  guardaxp:
    description: Guarde xp.
    aliases: [armazenarxp, guardalvl, armazenarlvl]
  retirarxp:
    description: Tira o xp.
    aliases: [tirarxp, retirarlvl, tirarlvl, pegarlvl]
  pa:
    description: Pega uma comandos.player.pa.
    aliases: [padeouro]