main: br.com.eterniaserver.eterniaserver.EterniaServer

name: EterniaServer
version: '1.0.0'
author: Yuri Nogueira
description: Blablabla
load: STARTUP
api-version: '1.13'
website: www.eterniaserver.com.br
depend: [EterniaLib, Vault, PlaceholderAPI]