main: eternia.EterniaServer

name: EterniaServer
version: '2.0.0'
author: Yuri Nogueira
description: Blablabla
api-version: '1.15'
depend: [Vault]
commands:
  suicide:
    description: Se mate.
    aliases: [suicidio, killme]
  advice:
    description: Avise.
    aliases: [broadcast, anuncio, aviso]
  donation:
    description: Doe.
    aliases: [doacao, doar, comprarvip]
  discord:
    description: Discord.
    aliases: [contato]
  rules:
    description: Regras.
    aliases: [regras]
  feed:
    description: Alimenta.
    aliases: [heal, fome]
  hat:
    description: Capacete.
    aliases: [capacete]
  name:
    description: Nome.
    aliases: [nickname, mudarnome, nome, changenickname]
  fly:
    description: Voe.
    aliases: [voar, ativarvoar, ativarfly]
  depositlvl:
    description: Guarde xp.
    aliases: [armazenarxp, guardalvl, armazenarlvl]
  withdrawlvl:
    description: Tira o xp.
    aliases: [tirarxp, retirarlvl, tirarlvl, pegarlvl]
  goldenshovel:
    description: Pega uma comandos.eternia.player.pa.
    aliases: [padeouro, pa]
  blocks:
    description: Transforma em bloco.
    aliases: [condenser, transformarembloco]
  back:
    description: Volta aonde morreu.
    aliases: [dback, voltarmorte]
  spectator:
    description: Va para o modo spectator.
    aliases: [inv, spect]
  survival:
    description: Volta ao modo survival.
    aliases: [jogar, aparecer]
  facebook:
    description: Pagina do server.
    aliases: [paginadoface]
  bottlexp:
    description: Garrafinhas de xp.
    aliases: [garrafinhas]
  colors:
    description: Descubra as cores.
    aliases: [cores]
  spawn:
    description: Se teleporta para o spawn.
    aliases: [inicio]
  setspawn:
    description: Define o spawn.
    aliases: [definirinicio]
  event:
    description: Vai para o evento.
    aliases: [evento]
  setevent:
    description: Define o local do evento.
    aliases: [definirevento]
  teleportall:
    description: Teleporta todos para tu.
    aliases: [tpall, teleportageral]
  arena:
    description: Vai pra arena.
    aliases: [pvp]
  setarena:
    description: Define a arena.
    aliases: [definirarena]
  crates:
    description: Vai pra caixas.
    aliases: [caixas]
  setcrates:
    description: Define a caixa.
    aliases: [setcaixas]
  vote:
    description: Vota.
    aliases: [votar, voto]
  teleportaccept:
    description: Aceita o tpa.
    aliases: [tpaccept, aceitartpa]
  teleportdeny:
    description: Nega o tpa.
    aliases: [tpdeny, negartpa]
  teleporttoplayer:
    description: Envia pedido de tpa.
    aliases: [tpa]
  checklevel:
    description: Verifica o saldo guardado.
    aliases: [verxp, checkxp, xpguardado]
  balance:
    description: Verifica seu dinheiro.
    aliases: [money, dinheiro, bal]
  pay:
    description: Paga dinheiro.
    aliases: [pagar]
  eco:
    description: Mexe no money.
    aliases: [economia]