main: eternia.EterniaServer

name: EterniaServer
version: '2.6.0'
author: Yuri Nogueira
description: Blablabla
api-version: '1.15'
depend: [Vault]
commands:
  suicide:
    description: Se mate.
    aliases: [suicidio, killme]
  advice:
    description: Avise.
    aliases: [broadcast, anuncio, aviso]
  donation:
    description: Doe.
    aliases: [doacao, doar, comprarvip]
  discord:
    description: Discord.
    aliases: [contato]
  rules:
    description: Regras.
    aliases: [regras]
  feed:
    description: Alimenta.
    aliases: [heal, fome]
  hat:
    description: Capacete.
    aliases: [capacete]
  name:
    description: Nome.
    aliases: [nickname, mudarnome, nome, changenickname]
  fly:
    description: Voe.
    aliases: [voar, ativarvoar, ativarfly]
  depositlvl:
    description: Guarde xp.
    aliases: [armazenarxp, guardalvl, armazenarlvl]
  withdrawlvl:
    description: Tira o xp.
    aliases: [tirarxp, retirarlvl, tirarlvl, pegarlvl]
  goldenshovel:
    description: Pega uma comandos.eternia.player.pa.
    aliases: [padeouro, pa]
  blocks:
    description: Transforma em bloco.
    aliases: [condenser, transformarembloco]
  back:
    description: Volta aonde morreu.
    aliases: [dback, voltarmorte]
  facebook:
    description: Pagina do server.
    aliases: [paginadoface]
  bottlexp:
    description: Garrafinhas de xp.
    aliases: [garrafinhas]
  colors:
    description: Descubra as cores.
    aliases: [cores]
  vote:
    description: Vota.
    aliases: [votar, voto]
  teleportaccept:
    description: Aceita o tpa.
    aliases: [tpaccept, aceitartpa]
  teleportdeny:
    description: Nega o tpa.
    aliases: [tpdeny, negartpa]
  teleporttoplayer:
    description: Envia pedido de tpa.
    aliases: [tpa]
  checklevel:
    description: Verifica o saldo guardado.
    aliases: [verxp, checkxp, xpguardado]
  pay:
    description: Paga alguem.
    aliases: [pagar]
  money:
    description: Ve seu ou de outro dinheiro.
    aliases: [balance]
  baltop:
    description: Ve o top money.
    aliases: [topmoney]
  eco:
    description: Meche na economia.
    aliases: [ecochange]
  spawnergive:
    description: Da um spawner.
    aliases: [darspawner]
  gamemode:
    description: Altera o gamemode de um jogador.
    aliases: [gm]
  rain:
    description: Altera o clima para chuvoso.
    aliases: [chuva]
  sun:
    description: Altera o clima para ensolarado.
    aliases: [sol]
  god:
    description: Ativa e desativa o godmode.
    aliases: [deus]
  thor:
    description: Puna as pessoas.
    aliases: [lightningbolt]
  warp:
    description: Vai para uma warp.
    aliases: [local]
  setwarp:
    description: Define uma warp.
    aliases: [setlocal]
  shop:
    description: Vai para uma loja.
    aliases: [loja]
  spawn:
    description: Se teleporta para o spawn.
    aliases: [inicio]
  setspawn:
    description: Define o spawn.
    aliases: [definirinicio]
  teleportall:
    description: Teleporta todos.
    aliases: [tpall]
  setshop:
    description: Define sua loja.
    aliases: [setloja]